---
# vars file for apps
base_apps:
  - zsh
  - vim
  - tmux
  - htop
  - yamllint

desktop_tools:
  - yakuake
  - synapse
  - deepin-terminal
  - x11vnc
  - snapd
  - evolution
  - evolution-ews

desktop_apps:
  - quentier
  - nextcloud-client
  - nextcloud-client-dolphin
  - kolourpaint
  - remmina
  - simplescreenrecorder
  - vlc
  - tigervnc-server

snap_classic_apps:
  - helm
  - kubectl
  - slack

snap_apps:
  - red-app
  - utube
  - telegram-desktop
  - youtube-music-desktop-app

vivaldi_version: '4.0.2312.38'
