---
- name: Install basic apps in the system
  become: True
  dnf:
    state: present
    name: "{{ item }}"
    update_cache: True
  loop: "{{ base_apps }}"
  tags:
    - base_apps

- name: Install desktop tools
  become: True
  dnf:
    state: present
    name: '{{ item }}'
    update_cache: True
  loop: '{{ desktop_tools }}'
  tags:
    - desktop
    - desktop-tools

- name: Install desktop apps
  become: True
  dnf:
    state: present
    name: '{{ item }}'
    update_cache: True
  loop: '{{ desktop_apps }}'
  tags:
    - desktop
    - desktop-apps
    - non-third-party

- name: Create Symbolic Link for snapd
  become: True
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
  tags:
    - desktop
    - desktop-apps
    - snapd-link

- name: Install zPrezto
  script: files/installPrezto.sh
  tags:
    - desktop
    - shell-plugins
    - prezto

- name: Install Vivaldi Browser
  become: True
  dnf:
    name: "https://downloads.vivaldi.com/stable/vivaldi-stable-{{ vivaldi_version }}.x86_64.rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - vivaldi

- name: Install Atom editor
  become: True
  dnf:
    name: "https://atom.io/download/rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - atom

- name: Install BoostNote notepad
  become: True
  dnf:
    name: "https://github.com/BoostIO/BoostNote.next/releases/latest/download/boost-note-linux.rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - boostnote

- name: Install GitKraken app
  become: True
  dnf:
    name: "https://release.gitkraken.com/linux/gitkraken-amd64.rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - gitkraken

- name: Download and unarchive Jetbrains Toolbox
  unarchive:
    src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.19.7784.tar.gz
    dest: ansible_env.HOME/Applications/
    remote_src: True
    create: True
  tags:
    - desktop
    - desktop-apps
    - toolbox

- name: Install Skype app
  become: True
  dnf:
    name: "https://go.skype.com/skypeforlinux-64.rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - skype

- name: Install Slack app
  become: True
  dnf:
    name: files/slack-4.12.0-0.1.fc21.x86_64.rpm
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - slack

- name: Install Zoom app
  become: True
  dnf:
    name: "https://zoom.us/client/latest/zoom_x86_64.rpm"
    state: present
    update_cache: True
    disable_gpg_check: True
  tags:
    - desktop
    - desktop-apps
    - zoom
